blank_issues_enabled: false

contact_links:
  - name: "\u2049 说明文档"
    url: "https://nepsyn.github.io/minaplay"
    about: "使用说明文档"
  - name: "\u2753 FAQ"
    url: "https://nepsyn.github.io/minaplay/guide/faq.html"
    about: "常见问题"
